#[cfg(test)]
mod tests {

    use core::core::convert;

    #[test]
    fn test_convert() {
        let css = r#"@font-face {
      font-family: 'iconfont'; /* Project id 4238197 */
      src: url('iconfont.woff2?t=1694760156045') format('woff2'),
           url('iconfont.woff?t=1694760156045') format('woff'),
           url('iconfont.ttf?t=1694760156045') format('truetype');
    }

    .iconfont {
      font-family: "iconfont" !important;
      font-size: 16px;
      font-style: normal;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

    .icon-foo:before {
      content: "\e601";
    }

    .icon-bar:before {
      content: "\e602";
    }
    "#;

        let result = convert("IconFonts", css, None);
        assert_eq!(result.is_ok(), true);
        assert_eq!(
            result.unwrap(),
            r#"// **************************************************************************
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by core
// **************************************************************************

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/widgets.dart';

@staticIconProvider
abstract final class IconFonts {
  IconFonts._();

  static const String _kFamily = 'iconfont';

  static const IconData iconFoo = IconData(0xe601, fontFamily: _kFamily);
  static const IconData iconBar = IconData(0xe602, fontFamily: _kFamily);
}"#
        );
    }
}
