name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Package
        run: |
          tar -czf ${{ matrix.os }}.tar.gz -C ./target/release .

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ matrix.os }}.tar.gz
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
